---
- name: Deploy Calculator App with Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker Image
      command: docker pull aayushi6402/calulator_miniproject:latest

    - name: Run Docker Container
      command: docker run -d --name calculator_miniproject aayushi6402/calulator_miniproject:latest /bin/bash