---
- name: Deploy Calculator App with Docker
  hosts: localhost
  become: false
  tasks:
    - name: Install Python Docker SDK
      pip:
        name: docker
        executable: pip3

    - name: Pull Docker Image
      docker_image:
        name: "aayushi6402/calculator_miniproject:latest"
        source: pull
      register: docker_pull_result
  
    # - name: Pull Docker Image
    #   command: docker pull aayushi6402/calculator_miniproject:latest


    - name: Stop and remove existing container if running
      shell: |
        docker ps -a --format '{{ "{{" }} .Names {{ "}}" }}' | grep -w calculator_miniproject && docker stop calculator_miniproject && docker rm calculator_miniproject || true
      ignore_errors: yes

    - name: Run Java Application Container
      # shell: docker run -it -d --name calculator 
      shell: docker run -it -d --name calculator_miniproject ayushi6402/calculator_miniproject /bin/bash

